import Vue from 'vue';
import Vuetify from 'vuetify/lib/framework';
import '@mdi/font/css/materialdesignicons.css';
import {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAvatar,
  VBadge,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VChip,
  VCol,
  VContainer,
  VDataTable,
  VDialog,
  VDivider,
  VFooter,
  VFileInput,
  VForm,
  VIcon,
  VImg,
  VList,
  VListItem,
  VListItemAvatar,
  VListItemContent,
  VListItemIcon,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VNavigationDrawer,
  VRow,
  VSelect,
  VSkeletonLoader,
  VSnackbar,
  VSpacer,
  VSubheader,
  VTextField,
  VTextarea,
  VToolbar,
  VToolbarTitle,
} from 'vuetify/lib/components';
import { Ripple } from 'vuetify/lib/directives';

const components = {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAvatar,
  VBadge,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VChip,
  VCol,
  VContainer,
  VDataTable,
  VDialog,
  VDivider,
  VFooter,
  VFileInput,
  VForm,
  VIcon,
  VImg,
  VList,
  VListItem,
  VListItemAvatar,
  VListItemContent,
  VListItemIcon,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VNavigationDrawer,
  VRow,
  VSelect,
  VSkeletonLoader,
  VSnackbar,
  VSpacer,
  VSubheader,
  VTextField,
  VTextarea,
  VToolbar,
  VToolbarTitle,
};

Vue.use(Vuetify, { components, directives: { Ripple } });

export default new Vuetify({
  theme: {
    dark: false,
    themes: {
      light: {
        primary: '#2563eb',
        secondary: '#f97316',
        accent: '#60a5fa',
        background: '#f8fafc',
        surface: '#ffffff',
        error: '#dc2626',
        success: '#16a34a',
        info: '#0ea5e9',
        warning: '#f59e0b',
      },
    },
  },
  icons: {
    iconfont: 'mdi',
  },
});
